### ISSUE TITLE
Add a Metropolis-within-Gibbs sampler

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aemcmc#26]
Following #16 we should implement a Metropolis-within-Gibbs sampler similar to PyMC's (algorithms listed in [this file](https://github.com/pymc-devs/pymc/blob/main/pymc/step_methods/__init__.py)) that uses NUTS to update the RVs with continuous variables and Gibbs samplers / others to update the RVs with discrete support.

This way we can start attracting users who will interact with a generic `build_sampler` (name tbd) function, and we will have a first performance benchmark. It will be a big step towards #3.

**Comment by rlouf** [comment]
The PyMC sampler is a Metropolis-within-Gibbs sampler, we separate the variables in different groups and sample from the conditional logprob of all these groups subsequently:
- *RVs with continuous support*: NUTS sampler

**Comment by rlouf** [comment]
Note that samplers other than NUTS won't be necessary if marginalisation of discrete RVs is implemented in https://github.com/aesara-devs/aeppl/issues/21 is

**Comment by brandonwillard** [comment]
> Note that samplers other than NUTS won't be necessary if marginalisation of discrete RVs is implemented in [aesara-devs/aeppl#21](https://github.com/aesara-devs/aeppl/issues/21) is

Unless I'm interpreting this issue and/or its comments incorrectly, we shouldn't need an explicit _sampler_ for this functionality.  

Instead, **we should have a generic _process_ that uses an internal sampling step database (i.e. #3) to find sampling steps for the relevant terms in a model graph, then applies NUTS&mdash;or any other generalizable sampling approach&mdash;to the remaining terms**.  The end result is likely to be a *-within-Gibbs approach to sampling the entire model, but it could also be an entirely Gibbs/NUTS-based approach as well.

How we arrive at a given full-model sampler ultimately will depend on our sampler-selecting heuristics and user-configurable settings.

**Comment by rlouf** [comment]
> Unless I'm interpreting this issue and/or its comments incorrectly, we shouldn't need an explicit _sampler_ for this functionality.  

The goal of this issue was to identify _a_ set of sampling steps that is sufficient to be able to sample any kind of model and make the library usable by anyone who is already using PyMC. The general framework is described in #3, and what is described here is by no means exhaustive.

**Comment by brandonwillard** [comment]
I updated the title to reflect the specificity of having a Metropolis-within-Gibbs sampler.

A general purpose sampler would definitely work as described in https://github.com/aesara-devs/aemcmc/issues/26#issuecomment-1176862939 and&mdash;more generally&mdash;#3, and it's the next thing on our list of most important things to do, especially since it's the definition of our user-facing entry point for this library.

**Comment by brandonwillard** [comment]
> The goal of this issue was to identify _a_ set of sampling steps that is sufficient to be able to sample any kind of model and make the library usable by anyone who is already using PyMC.

To be clear, such a set would necessarily consist of a subset of the samplers we have implemented in this library, and the general identification/production of these subsets is the focus of #3.

A general Metropolis-within-Gibbs sampler would not actually help with #3, because it wouldn't get us any closer to automatically assigning our existing samplers and/or a framework that would do so.

**Comment by rlouf** [comment]
I'm closing this because since #3 and after #47 we will effectively have that. We can open separate issues for the sampling steps mentioned above.
